### ISSUE TITLE
Package manager detection fails with pnpm Turbo repo 

### ISSUE THREAD

**Issue by mpaler** [egoist/detect-package-manager#13]
Sorry I don't have time to issue a PR at the present, but I'll describe my situation and workaround here just in case it helps someone.

My project is a [pnpm Turbo repo](https://turbo.build/repo/docs) for use on Vercel. It's composed of several apps and packages. In a Turbo repo, even though you can install and manage packages within each of the various apps and packages, with each app and package having their own package.json, the pnpm-lock.yaml only lives in the root of the monorepo.

Therefore if you wish to use `detect-package-manager` in one of your apps or packages, it will fail to detect pnpm as the package manager.

The quick workaround is to insert an empty pnpm-lock.json file in the package or app you wish to use `detect-package-manager`. I haven't tested this yet in prod, so I guess we'll see...

**Comment by AndreaPontrandolfo** [comment]
Related https://github.com/egoist/detect-package-manager/issues/12

@mpaler as a temporary workaround for some usecases, instead of adding a empty pnpm-lock.json in the workspace folder, you can specify the key `packageManager` in the the package.json.
Example: "packageManager": "pnpm@8.8.0".

**Comment by mpaler** [comment]
That feels a bit less hacky than my method! thanks for sharing.
